version: 2

# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w -X github.com/seungyeop-lee/directory-watcher/v2/cmd.version=v{{.Version}}

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^style:'
      - '^comment:'
      - '^docs:'
      - '^chore:'
      - '^test:'

brews:
  - repository:
      owner: seungyeop-lee
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"

dockers:
  - image_templates:
      - "ghcr.io/seungyeop-lee/directory-watcher:{{ .Version }}-amd64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"
    goarch: amd64
    extra_files:
      - entrypoint.sh
  - image_templates:
      - "ghcr.io/seungyeop-lee/directory-watcher:{{ .Version }}-arm64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm64"
    goarch: arm64
    extra_files:
      - entrypoint.sh

docker_manifests:
  - name_template: "ghcr.io/seungyeop-lee/directory-watcher:{{ .Version }}"
    image_templates:
      - "ghcr.io/seungyeop-lee/directory-watcher:{{ .Version }}-amd64"
      - "ghcr.io/seungyeop-lee/directory-watcher:{{ .Version }}-arm64"
  - name_template: "ghcr.io/seungyeop-lee/directory-watcher:latest"
    image_templates:
      - "ghcr.io/seungyeop-lee/directory-watcher:{{ .Version }}-amd64"
      - "ghcr.io/seungyeop-lee/directory-watcher:{{ .Version }}-arm64"
