global:
  lifeCycle:
    onStartWatch:
      - echo 'global onStartWatch'
    onBeforeChange:
      - echo 'global onBeforeChange'
    onAfterChange:
      - echo 'global onAfterChange'
    onFinishWatch:
      - echo 'global onFinishWatch'
watchTargets:
  - path: 'test/dir1'
    lifeCycle:
      onChange:
        - echo 'dir1 onChange'
  - path: 'test/dir2'
    lifeCycle:
      onStartWatch:
        - echo 'dir2 onStartWatch'
      onChange:
        - echo 'dir2 onChange'
      onFinishWatch:
        - echo 'dir2 onFinishWatch'
    option:
      excludeDir:
        - 'test/dir2/tmp'
      excludeSuffix:
        - '_test.go'
        - '~'
      waitMillisecond: 1000 # default 100
      watchEvent: CD
  - path: 'test/dir3'
    lifeCycle:
      onStartWatch:
        - echo 'dir3 onStartWatch'
      onChange:
        - dir: "cmd"
          cmd: "pwd"
      onFinishWatch:
        - dir: "internal"
          cmd:
          - "pwd"
          - "ls -al"
    option:
      watchSubDir: false
  - path: 'test/not_exist_dir'
    lifeCycle:
      onChange:
        - echo 'not_exist_dir onChange'
